### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/resvg#834]
Due to various reasons I will no longer be able to maintain this project. This includes even minor staff like accepting PRs and pushing releases.
Therefore I would like to transfer ownership to someone else. This includes giving an access to this repo, [svgtypes](https://github.com/RazrFalcon/svgtypes) repo and [simplecss](https://github.com/RazrFalcon/simplecss) repo + cargo packages.

If no one is interested in maintaining this project I will simply archive it for an unknown duration.

**Comment by waywardmonkeys** [comment]
I would like to bring this up in our Linebender office hours tomorrow and gauge our level of interest in being an umbrella for these crates.

**Comment by jackpot51** [comment]
@hecrj I believe resvg is critical for iced.

**Comment by doctorlard** [comment]
:blue_heart: :yellow_heart:

**Comment by waywardmonkeys** [comment]
We (Linebender) have discussed this in our last 2 weekly office hours and have been in touch with @RazrFalcon in email with questions and a proposal.

**Comment by RazrFalcon** [comment]
`resvg` is part of the [linebender](https://github.com/linebender) organization now.

**Comment by yisibl** [comment]
Any new plans for performance improvements or new features for the future?

**Comment by RazrFalcon** [comment]
@yisibl from who? I bet `resvg` would simply enter a hibernation state.

**Comment by yisibl** [comment]
> from who?
@RazrFalcon I mean for the new team.

>  I bet `resvg` would simply enter a hibernation state.
This is sad news. Anyway, resvg was a great project and thanks again for all your efforts on it.

**Comment by xStrom** [comment]
> Any new plans for performance improvements or new features for the future?
> I mean for the new team.

In the short term our focus is on the migration. There's plenty of maintenance related changes needed to make sure that `resvg` follows the Linebender standards and thus can continue to be fresh and open to contributions. As for performance or features, both are going to be unchanged in the short term.

Longer term we do have some ideas on how to improve things. However no specific plans to talk about yet.
