### ISSUE TITLE
Relicense resvg under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by DJMcNab** [linebender/resvg#838]
> [!NOTE]
>
> resvg has recently moved into the Linebender organisation. See #834 for details.
>
> We would also like to thank @RazrFalcon for all their previous work on resvg, and wish them luck in their future endeavours.

## What

As part of the move into Linebender, we are planning on relicensing resvg under the MIT/Apache 2.0 licenses.
These match the standard licenses used by Linebender, and it gives [maximum compatibility](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) with the rest of the Rust ecosystem.

**If you are mentioned in this issue, we need your help to make this happen**

To agree to this relicense, please read the details in this issue, then leave a comment with the following message:

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

This also follows a similar move done by wgpu. See [their issue](https://github.com/gfx-rs/wgpu/issues/1473) for their motivations, which broadly also apply to this project.

## MPL 2.0

For clarity, we are planning to remove the MPL 2.0 license requirement for new contributions, and so will no longer be releasing new code under the MPL.
This follows the precedent set by wgpu.
This will allow using code released under the standard MIT/Apache 2.0 license in this project.

For existing users, the Apache license is [documented as compatible](https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-bsd-and-apache) with the MPL,
so we expect that this change will only make resvg easier to use.
Additionally, this change does not (and cannot) remove the licenses for previous releases and commits, and so you can continue to use release 0.44.0 and earlier
under the MPL 2.0.

## Contributor checklist

- [x] @RazrFalcon
- [x] @LaurenzV
- [x] @gentoo90
- [x] @laurmaedje
- [x] `@ahaoboy`
- [x] `@akindle`
- [x] `@AnthonyMikh`
- [x] `@antmelnyk`
- [x] `@benoit-pierre` - reached by email by @DJMcNab 
- [x] `@CGMossa`
- [x] `@chubei-oppen`
- [x] `@conorgolden1`
- [x] `@CosmicHorrorDev`
- [x] `@dabreegster`
- [x] `@dhardy`
- [x] `@e00E`
- [x] `@enkore`
- [x] `@EpicEricEE`
- [ ] `@ferdnyc`
- [x] `@flxzt`
- [x] `@flying-sheep`
- [x] `@FylmTM`
- [x] `@growler`
- [x] `@harmic`
- [x] `@iamralpht`
- [x] `@JaFenix`
- [ ] `@jc86035`
- [x] `@JoKalliauer`
- [x] `@jpap`
- [x] `@jrmuizel`
- [x] `@kneitinger`
- [x] `@legoktm`
- [x] `@lu-zero`
- [x] `@mattfbacon`
- [x] `@mike-marcacci`
- [x] `@missdeer`
- [x] `@mmoult`
- [x] `@niklasf`
- [x] `@nnabeyang`
- [x] `@notjosh`
- [x] `@Nukesor`
- [x] `@nyurik`
- [x] `@ocohen`
- [x] `@real-or-random`
- [x] `@reknih`
- [x] `@selaux`
- [x] `@Shnatsel`
- [x] `@shuding`
- [x] `@ssssota`
- [x] `@Stoeoef`
- [x] `@therealbnut`
- [ ] `@Tibbel`
- [x] `@upsuper`
- [x] `@valpackett`
- [ ] `@velyan`
- [x] `@wez`
- [x] `@yisibl`
- [x] `@Zodey-hub`

We also need:
- [x] `Rémi Lauzier` - <https://github.com/linebender/resvg/commit/8a838f776aa0f1642a61d8becd802efffeb55b19>. Reached through email by @DJMcNab

If you are aware of any contributors not listed in this checklist, please let us know.

**Comment by RazrFalcon** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by laurmaedje** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by LaurenzV** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by DJMcNab** [comment]
You are getting this message because you previously contributed to resvg - an svg rendering library in Rust.
We are going through a relicensing process. We kindly ask you to please read this issue, and respond as directed in the initial comment. Thank you!

- @ahaoboy
- @akindle
- @AnthonyMikh
- @antmelnyk
- @benoit-pierre
- @CGMossa
- @chubei-oppen
- @conorgolden1
- @CosmicHorrorDev
- @dabreegster
- @dhardy
- @e00E
- @enkore
- @EpicEricEE
- @ferdnyc
- @flxzt
- @flying-sheep
- @FylmTM
- @growler
- @harmic
- @iamralpht
- @JaFenix
- @jc86035
- @JoKalliauer
- @jpap

**Comment by DJMcNab** [comment]
You are getting this message because you previously contributed to resvg - an svg rendering library in Rust.
We are going through a relicensing process. We kindly ask you to please read this issue, and respond as directed in the initial comment. Thank you!

- @jrmuizel
- @kneitinger
- @legoktm
- @lu-zero
- @mattfbacon
- @mike-marcacci
- @missdeer
- @mmoult
- @niklasf
- @nnabeyang
- @notjosh
- @Nukesor
- @nyurik
- @ocohen
- @real-or-random
- @reknih
- @selaux
- @Shnatsel
- @shuding
- @ssssota
- @Stoeoef
- @therealbnut
- @Tibbel
- @upsuper
- @valpackett
- @velyan
- @wez
- @yisibl
- @Zodey-hub

**Comment by CosmicHorrorDev** [comment]
Thanks for the ping!

---

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by growler** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Zodey-hub** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ssssota** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by upsuper** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by FylmTM** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by kneitinger** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by flying-sheep** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by CGMossa** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by e00E** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by missdeer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by EpicEricEE** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ahaoboy** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by harmic** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by notjosh** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

---

glad to see resvg live on <3 thank you @RazrFalcon for all your work on this

**Comment by flxzt** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by reknih** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by nnabeyang** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Nukesor** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mattfbacon** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by selaux** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by lu-zero** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by JaFenix** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ocohen** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to choose either at their option.

**Comment by real-or-random** [comment]
nit: I'm happy to make that statement (as I've done in the previous comment), but I think technically it'll be more correct to restrict it to past contributions: 
```
I license past contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```
It's hard to predict what will happen in the future, so I'm not sure if everyone is comfortable making a statement about the future. But future contributions will, of course, be anyway covered by the "inbound=outbound" rule, which is also [made explicit in the GitHub ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license).

Or if you're worried about currently open PRs etc., perhaps this:
```
I license past contributions, and until further notice also future contributions, under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

Feel free to ignore me. As I said, I'm fine with the statement, I just want to help.

**Comment by iamralpht** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ferdnyc** [comment]
Because the statement is in a text block and not wrapped, I can't read the whole thing in the Android app. Put me down for don't care / do whatever

**Comment by jrmuizel** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by nyurik** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by yisibl** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by DJMcNab** [comment]
@real-or-random thanks for the input. I think just using the wording that wgpu used is easier for us, and minimises the risk of.

Fwiw, no-one had an issue with the wording for either Bevy or wgpu, so I don't think it's likely to be an issue.

**Comment by conorgolden1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by AnthonyMikh** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

_it is not like I feel that my single typo fix is that significant in grand scheme of things but oh well_

**Comment by niklasf** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by dhardy** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Stoeoef** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by valpackett** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by antmelnyk** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by gentoo90** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by jpap** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mike-marcacci** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by wez** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by JoKalliauer** [comment]
I consider my [past edit](https://github.com/linebender/resvg/commits/main/?author=JoKalliauer) (on Readme.md) below the "Threshold of originality" (i.e. [Public Domain](https://en.wikipedia.org/wiki/Public_domain)), therefore:


> I license past contributions under the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license, which allows using my past contributions under both [MIT](https://en.wikipedia.org/wiki/MIT_License) aswell [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0).
> 
> I license future contributions under the dual [MIT](https://en.wikipedia.org/wiki/MIT_License)/[Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) license, allowing licensees to choose either at their option.

With MIT-License I mean any of the Version of "[Expat License](https://en.wikipedia.org/wiki/MIT_License#License_terms)" or "[X11 License](https://en.wikipedia.org/wiki/MIT_License#X11_License)" or the MIT-License on Github.

**Comment by DJMcNab** [comment]
@JoKalliauer thanks for responding. Unfortunately, I'm not certain that the CC0 is compatible with the Apache 2.0; in particular, it has limitations around patent grants, which the Apache 2.0 license requires. It might be fine, but it makes things more complicated for us.
You are of course free to license your past contribution under CC0, and thank you for doing so. However, I would also please ask you respond with the exactly requested text (without any links and outside a quote), which will make things easier for us.

Indeed, we are meaning the expat license here, with SPDX identifier `MIT`.

**Comment by JoKalliauer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mmoult** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by legoktm** [comment]
Same, my only commit (https://github.com/linebender/resvg/commit/8d363ef3ef451150e9bc5ab72e3d7ef4ba896584) is below the threshold of originality as well. In any case:

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by DJMcNab** [comment]
@chubei can you confirm whether @chubei-oppen was your account? If so, please read this issue and respond accordingly.

**Comment by chubei** [comment]
Hi @DJMcNab thank you for the ping. @chubei-oppen was my account and

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by enkore** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by sorairolake** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by DJMcNab** [comment]
Thank you all for taking part in this! We have now completed this relicense, which was implemented in #844. See [the Zulip thread](https://xi.zulipchat.com/#narrow/channel/465085-resvg/topic/Relicensing.20resvg) for discussion of the people we were unable to reach.

For clarity, these were:
- @jc86035, who contributed #130. Those small grammar fixes are not copyrightable
- @Tibbel, who contributed #163. That code is extremely standard boilerplate which is not copyrightable.
- @velyan, who contributed #158; the Skia backend has been removed, alongside that README file.
- @ferdnyc, who did agree to the relicense but used their own wording. We've decided that their wording is sufficiently clear in context for us to accept.

**Comment by flying-sheep** [comment]
Question!

If I understand correctly:

- MIT is for compatibility with the GPL family
- Apache-2.0 is for copyright clause and lack of headers(?)

The MPL-2.0 is also compatible with the GPL licenses, so why didn’t you go MPL-2.0/Apache-2.0?

**Comment by DJMcNab** [comment]
Largely, the MIT/Apache-2.0 choice as a whole is for compatibility with other crates (e.g. Vello, Iced), so that code can be copied moved into dependent crates more easily.
