### ISSUE TITLE
Help Request: Save svg resized to bounding box

### ISSUE THREAD

**Issue by jeff8j** [linebender/resvg#854]
I have the svgs showing in my program resvg works great thank you so much
I use the bounding box to show the svg trimmed

Is there a way I can out put the results of to_string but trimmed like how I show it?
If resvg cant is there some way maybe I can edit the output string to put something in the svg to show it like that?

Thank you

**Comment by jeff8j** [comment]
I ended up outputting it to a string adding the viewBox to the string then reloading it and saving it. It has the desired output.

**Comment by RazrFalcon** [comment]
Yes, it's not possible and not planned.

**Comment by jeff8j** [comment]
Is it possible to do svg manipulation on a lower level in usvg?

**Comment by RazrFalcon** [comment]
usvg isn't designed for editing.
