### ISSUE TITLE
Specific SVG wont load

### ISSUE THREAD

**Issue by jeff8j** [linebender/resvg#855]
I came across a svg that wont load
resvg_parse_tree_from_file has an error code of 1
It probably just a weird type of svg not sure if this is an issue that matters

![testc](https://github.com/user-attachments/assets/180ab325-115c-4693-b199-968454c5807b)

`<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="300mm" height="300mm" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
viewBox="0 0 30000 30000"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:xodm="http://www.corel.com/coreldraw/odm/2003">
 <defs>
  <style type="text/css">
   <![CDATA[
    .str0 {stroke:black;stroke-width:7.62;stroke-miterlimit:2.61313}
    .fil0 {fill:black}
   ]]>
  </style>
 </defs>
 <g id="Layer_x0020_1">
  <metadata id="CorelCorpID_0Corel-Layer"/>
  <path class="fil0 str0" d="M11872.66 22331.73c201.75,-639.39 159.42,-1334.97 -114.03,-1941.11 -3.87,-110.19 -7.12,-342.77 -9.77,-452.97 122.81,111.27 177.9,203.25 343.89,117.48 375.08,-193.82 -357.86,-1464.24 1182.9,-2797.6 -136.56,1102.83 66.97,2385.99 1088.55,3018.5 0.52,756.79 -1,1515.8 -24.53,2269.72 -6.75,216.04 -8.12,754.09 -153.85,929.85 -52.93,63.84 -139.42,107.86 -217.28,138.95l0 -583.92c0,-149.95 -122.66,-272.61 -272.62,-272.61 -149.96,0 -272.62,122.66 -272.62,272.61l0 694.04c-162.02,11.19 -324.51,7.87 -465.45,-6.41l0 -687.63c0,-149.95 -122.66,-272.61 -272.62,-272.61 -149.96,0 -272.62,122.66 -272.62,272.61l0 540.19c-176.53,-90.08 -321.64,-225.89 -408.4,-427.26 -93.05,-215.99 -124.11,-516.05 -131.55,-811.83zm5088.84 -1655.2c58.3,-122.8 -919.16,-2080.01 28.11,-3585.7 488.1,360.44 890.52,816.95 1066.71,1390.87 196.68,640.66 -194.01,1385.49 235.35,1552.88 231.43,90.23 448.26,-126.47 640.03,-254.55 -3.05,160.45 -7.22,320.91 -12.48,481.3 -345.13,668.3 -403.15,1448.04 -146.05,2161.35 -3.46,149.22 -8.85,298.19 -17.23,446.55 -19.88,351.94 -25.73,607.18 -371.46,745.34l0 -583.94c0,-149.95 -122.65,-272.61 -272.61,-272.61 -149.97,0 -272.63,122.66 -272.63,272.61l0.01 697.47c-160.14,13.35 -321.96,14.11 -465.46,6.35l0 -703.82c0,-149.94 -122.66,-272.61 -272.61,-272.61 -149.97,0 -272.63,122.66 -272.63,272.61l0 606.84c-296.38,-110.84 -460.37,-326.21 -564.8,-727.79 -149.09,-573.35 -146.82,-1473.97 -138.69,-2096.07 261.84,39.06 701.86,146.42 836.44,-137.08zm2575.94 -1355.17c290.36,-264.59 419.31,-488.42 549.54,-843.9 92.49,161.41 163.71,331.98 225.43,508.39 -286.28,116.99 -548.23,281.25 -776.13,483.09 0.49,-49.19 0.87,-98.39 1.16,-147.58zm-9154.95 649.39c260.37,-280.32 581.31,130.89 550.56,579 -42.3,615.32 -760.55,793.92 -760.52,56.73 1,-222.86 88.19,-504.67 209.96,-635.73zm-228.84 -2006.86c-169.8,270.03 -283.28,550.93 -384.66,865.55 -343.35,-63.2 -699.55,-59.98 -1041.09,9.24 -238.94,-94.53 -438.88,-259.01 -599.81,-493.4 45.73,-62.45 85.99,-129 119.85,-199.14 328.92,217.24 472.18,71.96 452.92,-284.66 -74.74,-1268.25 897.63,-2379.65 1795.65,-2961.29 -385.77,1151.94 -537.54,2298.87 -342.86,3063.7zm937.71 -4030.82c-1439.82,460.28 -2382.21,1453.12 -2827.14,2978.52 -347.06,-938.12 -202.28,-2713.77 511.83,-3416.12 492.67,-655.94 558.37,-711.41 -198.74,-835.95 -695.1,-37.34 -1526.06,48.31 -2019.03,598.09 30.37,-230.83 87.62,-458.76 160.72,-678.56 453.01,-1362.07 1729.67,-1845.82 3089.92,-1770.77 191.09,1088.8 605.17,2323.85 1282.44,3124.79zm-2817.82 -707.21c-610.28,613.03 -840.73,1490.14 -876.05,2337.66 -224.7,-241.89 -483.02,-448.76 -768.36,-569.22 -471.26,-198.96 -984.55,-155.43 -1461.14,-4.52 -270.19,85.55 -524.03,224.67 -536.14,555.89 -7,191.21 74.5,328.64 197.79,430.45 -92,45.14 -180.44,98.15 -259.64,157.79 -235.97,177.67 -405.24,453.85 -289.93,757.61 158.65,417.91 621.64,385.36 925.66,458.57 33.91,82.77 66.71,210.23 97.8,285.83 145.46,353.62 408.53,705.08 713.25,938.47 386.8,296.25 878.6,428.04 1353.73,292.44 108.96,145.01 226.01,278.74 351.14,401.17 -1632.97,1131.34 -1546.4,3580.02 166.36,4591.56l-1852.88 0 0 551.26 18729.16 0 0 -551.26 -2036.91 0c803.12,-474.32 1341.85,-1348.78 1341.85,-2349.06 0,-1690.11 -1519.87,-2967.62 -3181.44,-2688.35 -141.12,-414.74 -313.2,-772.75 -624.86,-1130.06 63.54,-696.78 -103.35,-1398.69 -408.71,-2050.99 421.17,21.78 828.12,152.86 1147.88,453.74 459.76,432.6 772.4,1015.44 739.49,1624.9 -66.83,1237.61 1234.03,-164.61 1314.22,-1514.79 61.5,-1035.34 -104.91,-2207.35 -869.28,-2975.17 1450.66,-22.34 1587.54,1050.75 2046.16,985.26 395.67,-56.51 310.47,-1438.37 172.59,-1852.97 -393.65,-1183.61 -1310.99,-1913.55 -2510.29,-2161.59 1904.09,-429.64 3105.8,950.64 3273.52,687.08 792.3,-1244.97 -951.99,-3061.55 -1873.92,-3571.54 587.73,-120.22 1338.65,18.43 1870.91,278.78 266.78,130.49 567.3,584.13 695.68,52.18 332.94,-1658.33 -969.18,-2872.7 -2617.33,-2936.66 477.35,-207.84 1576.79,-578.52 1563.76,-867.77 -24.31,-539.45 -2633.07,-936.1 -3049.63,-951.24 -1276.88,-46.42 -2450.47,643.21 -3198.84,1647.09 167.42,-1415.84 2397.27,-2285.84 2380.12,-2933.62 -8.5,-321.4 -2030.83,-162.49 -2440.6,-33.64 -601.08,189.02 -1156.28,517.92 -1579.6,983.16 -326.18,-694.87 -895.18,-1201.83 -1594.25,-1504.77 -362.87,-157.24 -1835.53,-581.74 -2093.62,-141.46 -178.76,304.93 615.34,1082.56 732.74,2233.91 -968.06,-1747.25 -4407.06,-2260.47 -4449.75,-1508.06 -26.75,471.5 1644.75,1402.61 2129.88,2166.75 151.85,239.17 227.33,483.97 256.87,733.8 -2133.34,-2861.75 -6083.91,-1095.25 -5957.43,-656.14 81.07,281.46 795.34,620.17 1272.7,828.06 -1637.12,63.55 -3118.94,1206.59 -2616.17,2976.35 122.38,342.67 506.25,95.37 767.3,-32.33 532.28,-260.36 1210.42,-458.54 1798.16,-338.32 -666.6,368.72 -1293.66,1116.34 -1763.57,1709.52 -361.04,455.75 -416.65,1692.92 -110.36,1822.34 471.79,199.34 1369.42,-1077.04 3273.52,-647.4 -1199.28,248.03 -2116.67,978 -2510.3,2161.58 -137.88,414.6 -54.2,1604.64 198.28,1772.82 397.68,264.92 569.79,-927.43 2020.48,-905.09zm6673.92 9045.59c13.78,-571.46 16.54,-1145.24 16.76,-1718.28 183.19,62.82 372.88,112.64 562.39,153.7 -8.05,496.49 -8.48,1109.34 35.62,1606.33 -226.01,50.57 -400.36,37.08 -614.77,-41.75zm-304.81 -2650.82c-895.76,-648.77 -928.38,-3068.09 -187.35,-3768.09 578.06,125.82 1428.04,510.77 1942.96,790.75 -621.97,990.5 -688.56,2363.3 -309.21,3456.49 -485.08,-77.6 -1064.73,-202.71 -1446.4,-479.15zm5580.65 3697.25c-345.54,-90.78 -572.27,-401.6 -506.09,-693.84 119.87,-529.4 1146.96,-1385.45 1611.55,-1259.29 356.59,117.68 1012.19,1387.73 892.31,1917.14 -66.15,292.22 -400.26,455.71 -745.81,364.92 -313,-82.23 -439.52,-255.68 -536.08,-561.51 -216.4,223.61 -402.89,314.84 -715.88,232.58zm-589.43 -2759.57c-30.75,-448.11 290.19,-859.32 550.56,-579 121.78,131.06 208.97,412.87 209.96,635.73 0.03,737.19 -718.22,558.59 -760.52,-56.73zm-6146.67 -4323.05c-995.3,591.37 -1772.28,1424.35 -1859.94,2658.78 -971.52,-895.49 -1017.27,-2317.7 -304.55,-4266.62 114.56,-48.43 233.15,-94.93 355.73,-139.51 229.89,173.8 472.42,319.14 727.7,466.33 404.49,428.41 845.85,659.5 1364.12,797.79 -111.96,118.78 -206.31,279.87 -283.06,483.23zm5358.88 2749.53c-11.27,-286.92 -67.26,-571.48 -165.2,-841.95 -398.5,-1100.51 -1407.9,-1820.95 -2452.08,-2289.13 1226.82,-204.06 1596.24,-617.3 2029.58,-1015.24 1136.86,863.08 1744.78,2334.44 1045.45,3683.59 -86.05,166.03 -304.18,346.69 -457.75,462.73zm40.79 -4575.33c509.54,-413.21 861.95,-930.89 1134.77,-1524.83 267.79,-582.97 496.65,-1315.58 629.49,-2072.42 1360.23,-75.05 2636.93,408.68 3089.93,1770.76 73.1,219.81 130.35,447.74 160.72,678.56 -578.42,-645.07 -1367.9,-717.32 -2199.65,-573.57 -944.8,319 -142.93,630.05 216.52,1284.52 406.13,739.46 483.47,1432.17 438.4,2190.95 -14.88,250.61 -70.44,503.94 -157.61,742.28 -307.15,-1438.4 -1385.77,-2024.15 -2786.97,-1934.94 -151.75,-187.5 -326.96,-374.61 -525.6,-561.31zm-7701.81 4987.25c0.05,8.88 -44.53,119.48 -44.47,128.38 -231.99,-218.39 -502.29,-396.57 -799.71,-523.41 33.94,-104.51 70.8,-287.51 112.48,-388.78 154.8,259.49 460.62,520.35 731.7,783.81zm-1646.83 -13.74c148.02,65.52 256.86,342.95 276.74,588.87 20.25,250.44 -76.63,1034.73 -461.79,740.71 -416.7,-318.48 -291.35,-1540.79 185.05,-1329.58zm-2113.24 -2964.13c57.95,443.92 212.41,896.21 440.17,1277.8 -43.99,369.02 -356.2,630.05 -686.18,703.15 -633.38,140.32 -1197.75,-430.71 -1413.04,-954.08 -101.54,-246.86 -103.96,-449.16 -322.76,-542.92 -218.79,-93.76 -654,-78.96 -695.66,-188.72 -41.67,-109.75 310.17,-344.03 635.36,-400.27 325.19,-56.24 623.73,65.57 769.77,117.57 146.04,52.02 139.58,34.24 129.72,-47.5 -9.84,-81.75 -23.1,-227.45 -226.85,-367.63 -203.74,-140.16 -597.97,-274.8 -789.84,-358.64 -191.84,-83.83 -181.34,-116.87 53.25,-191.15 234.61,-74.29 693.3,-189.86 1115.73,-11.52 379.24,160.11 729.27,557.11 990.33,963.91zm9886.67 -1600.26c-961.92,706.3 -3203.27,700.95 -4163.26,-3.93 -335.52,-246.36 -611.8,-607.51 -807.35,-1003.53 188.7,119.9 385.01,227.13 597.78,298.32 340.15,113.81 716.51,132.96 1069.12,72.68 569.31,-97.32 1034.64,-395.78 1294.17,-916.99 259.53,521.21 724.86,819.67 1294.17,916.99 525.69,89.86 1000.46,6.08 1461.03,-248.24 -190.26,348.96 -444.02,663.22 -745.66,884.7zm-1333.44 -1379.39c-302.95,-266.14 -412.12,-616.36 -426.17,-1006.53 146.58,-70.45 407.12,-217.96 669.23,-357.78 958.26,-511.16 719.62,-1023.48 204.71,-1393.02 552.87,50.05 1133.99,157.77 1478.72,427.3 534.66,418.03 609.58,1237.58 497.59,1858.12 -15.5,85.88 -35.3,172.71 -59.15,259.69 -252.05,174.74 -524.88,367.36 -817.34,465.21 -485.52,162.44 -1153.36,93.33 -1547.59,-252.99zm287.09 -1994.81c-99.68,105.75 -724.05,634.83 -727.61,281.12 -2.23,-221.65 179.45,-507.84 -75.02,-780.53 -137.03,-146.84 -501.38,-330.46 -102.53,-303.16 325.48,22.3 839.16,139.34 993.35,464.12 51.81,109.14 38.59,203.95 -88.19,338.45zm705.63 -1299.77c-959.37,-154.51 -2427.51,-170.43 -3390.35,-26.44 151.63,-175.37 248.55,-443.06 248.55,-742.99 0,-528.28 -300.63,-956.53 -671.47,-956.53 -370.84,0 -671.47,428.25 -671.47,956.53 0,406.15 177.7,753.19 428.39,891.92 -271.6,85.86 -521.71,203.56 -728.79,365.46 -721.3,563.96 -872.3,1585.3 -718.5,2437.37 32.75,181.42 80.89,364.72 143.21,545.72 -1047.5,-1166.04 -1613.29,-3890.79 -1170.26,-5320.28 325.04,-1048.76 1325.38,-1828.96 2400.03,-1981.87 934.37,-132.94 1839.02,720.02 2370.16,835.92 596.19,-86.36 1093.36,-1019.23 2409.35,-831.99 1074.65,152.91 2074.99,933.1 2400.03,1981.86 443.05,1429.55 -122.78,4154.18 -1170.27,5320.29 62.32,-181 110.46,-364.28 143.21,-545.72 153.8,-852.07 2.83,-1873.43 -718.49,-2437.38 -231.61,-181.09 -517.14,-304.49 -826.36,-389.91 300.87,-94.7 525.96,-476.91 525.96,-934.01 0,-528.28 -300.63,-956.53 -671.47,-956.53 -370.84,0 -671.47,428.25 -671.47,956.53 0,356.56 136.96,667.56 340.01,832.05zm-7732.77 11211.58c464.59,-126.16 1491.67,729.89 1611.54,1259.29 66.19,292.24 -160.55,603.06 -506.09,693.84 -312.99,82.26 -499.48,-8.97 -715.88,-232.58 -96.56,305.83 -223.08,479.27 -536.08,561.51 -345.55,90.79 -679.66,-72.7 -745.81,-364.92 -119.88,-529.41 535.72,-1799.46 892.32,-1917.14zm-1232.98 -1496.1c304.38,-447.72 1002.76,525.08 801.22,1030.83 -186.45,467.16 -648.6,-147.79 -752.49,-372.9 -102.02,-221.04 -143.36,-518.92 -48.73,-657.93zm1692.7 -10770.51c-15.94,245.31 -15.74,498.9 -1.62,755.78 -1347.81,-604.29 -2687.57,-608.96 -3944.1,179.74 48.85,-229.9 133.61,-458.3 242.03,-630.41 432.67,-686.87 1215.95,-1449.42 2011.29,-1674.8 207.88,757.78 880.7,1323.09 1692.4,1369.69zm57.41 -497.82c-731.52,-26.99 -1316.26,-628.97 -1316.26,-1367.63 0,-755.84 612.27,-1368.56 1367.55,-1368.56 493.29,0 925.58,261.39 1166.12,653.28 -168.52,135.87 -323.05,285.16 -461.73,446.81 -108.12,-283.92 -382.72,-485.65 -704.39,-485.65 -416.16,0 -753.54,337.64 -753.54,754.11 0,460.75 408.81,812.78 863.7,746.1 -72.75,200.51 -124.52,405.07 -161.45,621.54zm11008.48 1257.53c14.12,-256.89 14.34,-510.46 -1.6,-755.77 811.8,-46.62 1484.48,-612.21 1692.37,-1369.72l47.52 13.47c877.75,248.77 2007.48,1358.3 2205.83,2291.76 -1256.53,-788.7 -2596.31,-784.03 -3944.12,-179.74zm643.24 -2621.24c0,-416.47 -337.39,-754.11 -753.55,-754.11 -321.66,0 -596.27,201.71 -704.38,485.63 -138.68,-161.65 -293.21,-310.93 -461.74,-446.8 240.55,-391.9 672.84,-653.28 1166.13,-653.28 755.28,0 1367.54,612.73 1367.54,1368.57 0,738.65 -584.73,1340.64 -1316.25,1367.63 -36.89,-216.25 -88.73,-421.22 -161.44,-621.54 455.15,66.6 863.69,-285.51 863.69,-746.1zm1082.06 -345.82c-162.12,-866.39 -922.14,-1522.74 -1835.6,-1522.74 -662.75,0 -1244.73,345.52 -1576.18,866.06 -156.42,-94.77 -321.22,-179.41 -491.18,-251.78 437.82,-1315.06 1713.03,-2435.02 3146.44,-2382.92 530.78,19.3 1183.02,156.96 1697.88,300.37 -579.33,194.48 -1221.3,508.66 -1402.16,1133.3 -95.12,328.52 -64.45,353.96 231.92,293.86 1128.57,-228.89 3014.59,406.19 3091.53,1683.63 -881.6,-420.17 -1981.9,-635.14 -2862.65,-119.78zm-7863.06 6556.96c-394.23,346.32 -1062.07,415.43 -1547.59,252.99 -337.93,-113.06 -690.61,-377.38 -991.06,-585.61 -11.15,-47.92 -21.04,-95.72 -29.61,-143.22 -112.02,-620.54 -37.06,-1440.09 497.6,-1858.11 328.61,-256.93 872.04,-366.83 1401.01,-419.9 -480.45,327.24 -715.85,782.39 268.48,1307.45 430.03,229.38 646.82,369.55 828.12,414.96 -10.99,399.51 -116.21,758.46 -426.95,1031.44zm2612.95 -7744.96c140.95,-776.66 126.28,-1572.06 -51.53,-2342.1 348.98,-550.12 905.73,-919.67 1521.22,-1113.23 300.46,-94.49 613.46,-152.92 929.57,-193.87 -1498.81,1102.96 -1984.98,1824.39 -1701.91,3720.18 -232.5,-50.57 -469,-75.91 -697.35,-70.98zm-738.22 125.73c-435.51,140.64 -834.17,386.37 -1267.73,671.55 -155.09,-687 -461.05,-1668.79 -706.21,-2283.88 203.03,-1050.31 172.79,-1512.76 -473.72,-2793.61 339.45,58.6 672.15,138.59 993.38,277.79 515.17,223.25 947.19,586.07 1204.91,1090.47 452.36,885.33 452.42,2078.8 249.37,3037.68zm-2980.26 3290.45c0,152.11 -125.72,275.43 -280.8,275.43 -155.07,0 -280.79,-123.32 -280.79,-275.43 0,-152.1 125.72,-275.42 280.79,-275.42 155.08,0 280.8,123.32 280.8,275.42zm809.89 -3103.77c-182.41,-118.43 -473.93,-237.36 -748.99,-282.95 -333.02,-55.14 -679.53,-42.56 -1040.36,33.88 25.31,-666.73 168.26,-1521.84 -306.01,-2332.08 -301.41,-514.93 -869.7,-984.44 -1413.19,-1384.4 2305.09,298.68 3036.77,1831.69 3508.55,3965.55zm-4523.79 -651.07c-913.32,0 -1673.52,655.97 -1835.62,1522.73 -880.74,-515.36 -1981.04,-300.39 -2862.64,119.78 73.68,-1223.44 1740.05,-1862.95 2787.05,-1706.49 346.03,11.43 623.95,102.32 562.86,-165.16 -144.79,-633.98 -849.27,-1044.64 -1428.61,-1239.14 2080.9,-579.64 4059.32,-275.26 4844.32,2082.54 -169.95,72.36 -334.71,156.99 -491.11,251.75 -331.47,-520.63 -913.56,-866.01 -1576.25,-866.01zm-2237.55 15480.13c167.35,43.49 378.11,235.05 486.79,424.69 356.7,629.13 -342.7,879.94 -676.51,378.54 -243.06,-365.17 -168.12,-896.3 189.72,-803.23zm14942.05 433.25c108.68,-189.64 319.45,-381.2 486.79,-424.69 357.84,-93.07 432.79,438.06 189.73,803.23 -333.82,501.4 -1033.22,250.59 -676.52,-378.54zm-1759.14 -1288.55c19.88,-245.92 128.72,-523.35 276.74,-588.87 476.4,-211.21 601.75,1011.1 185.05,1329.58 -385.16,294.02 -482.04,-490.26 -461.79,-740.71zm1008.56 919.08c-201.54,-505.75 496.84,-1478.55 801.22,-1030.83 94.63,139.01 53.29,436.89 -48.73,657.93 -103.89,225.11 -566.04,840.06 -752.49,372.9zm-10366.07 2322.54c79.41,252.35 208.04,464.48 392.8,637.54l-1130.56 0c282.66,-166.93 532.57,-383.44 737.76,-637.54zm3252.44 637.54c207.87,-246.37 261.79,-627.95 280.51,-968.83 246.05,64.47 475.58,70.01 720.5,20.36 81.22,383.13 214.33,706.52 444.69,948.47l-1445.7 0zm2574.61 -14473.72c-162.83,0 -294.83,-129.49 -294.83,-289.21 0,-159.71 132,-289.2 294.83,-289.2 162.84,0 294.84,129.49 294.84,289.2 0,159.72 -132,289.21 -294.84,289.21zm1845.73 14473.72c131.73,-153.32 201.53,-335.09 240.74,-534.99 187.41,210.09 406.87,390.99 650.71,534.99l-891.45 0z"/>
  <polygon class="fil0 str0" points="24764.29,28452.04 6035.13,28452.04 6035.13,29003.3 24764.29,29003.3 "/>
 </g>
</svg>`

**Comment by LaurenzV** [comment]
It's because the file specifies an encoding of UTF-16, but `resvg` only supports UTF-8.

**Comment by DJMcNab** [comment]
I suppose we can leave this issue open to track fixing up the error messages here, because if the only feedback is "an error code of 1", that's not great.

**Comment by RazrFalcon** [comment]
>because if the only feedback is "an error code of 1", that's not great.

The user is using C API. That's why the error is so bad.

Also, the readme explicitly states that only UTF-8 files are supported.

**Comment by DJMcNab** [comment]
Thanks! This error case is clearly documented. I don't think there's anything to action in this issue.

To fix this, you should convert your SVG file from utf-16 into utf-8 before providing it to resvg.
