### ISSUE TITLE
How to get the origin pixels values from pixmap?  Is that possible?

### ISSUE THREAD

**Issue by flywithmesy** [linebender/resvg#858]
How to get the final image pixels from pixmap?
Is that possible? Would you please tell me?
Now I could get the PNG file with the pixmap in the resvg project,  but I couldn't read the pixel from pixmap now and I just want to convert svg to raster image. And the input svg may is the group of raster image and vector graphics, and I want to be able to perform image pixel manipulation on the converted raster image data.

**Comment by RazrFalcon** [comment]
See https://github.com/linebender/resvg/blob/main/crates/resvg/examples/minimal.rs
The `pixmap` variable would have your pixels.

**Comment by flywithmesy** [comment]
Yes, but I would like to tunning pixels directly in the pixmap, but they are priviate, not allow me to modify them, how to do that?

**Comment by DJMcNab** [comment]
I think you want the [`red`](https://docs.rs/tiny-skia/0.11.4/tiny_skia/struct.PremultipliedColorU8.html#method.red) method.

**Comment by flywithmesy** [comment]
Yes, I would like to get the red, green, and blue pixel values for all pixels from the pixmap.
Could you please tell me how to modify that?

**Comment by DJMcNab** [comment]
I think you should be using [`pixels_mut`](https://docs.rs/tiny-skia/0.11.4/tiny_skia/struct.PixmapMut.html#method.pixels_mut) here. You should be able to replace the pixels if you use the method to get exclusive access to them, but of course you can't mutate them from a shared reference.
