### ISSUE TITLE
Is it possible to safely use one fontdb database in multiple different usvg::Options?

### ISSUE THREAD

**Issue by ANSH3LL** [linebender/resvg#863]
Hello, I'd like to create a single `fontdb` database and use it every time I create a `usvg::Tree`.
This is for the purpose of avoiding memory wastage by loading the same fonts multiple times when rendering different SVGs.
Is this possible? Please provide a code snippet if it's not too much work.
Also, how can I safely dispose this database when I'm done?
Thank you :)

**Comment by RazrFalcon** [comment]
`fontdb` doesn't load fonts into memory, unless you have explicitly done so, so nothing is wasted.

And yes, it's safe to put `fontdb` into multiple `usvg::Options`. At least for now. The API might change in the future.

>Also, how can I safely dispose this database when I'm done?

Rust will deallocate it automatically. If that was your question.

>Please provide a code snippet if it's not too much work.

[Like this](https://github.com/linebender/resvg/blob/cf024df1e0e94abbe604f1395a2307702c9955d5/crates/resvg/tests/integration/main.rs#L18)?

**Comment by ANSH3LL** [comment]
> `fontdb` doesn't load fonts into memory, unless you have explicitly done so, so nothing is wasted.

I am using the C-API and so every time I create a new `usvg::Tree` with new `usvg::Options` (using `resvg_options_create`), a new `fontdb` database is created. 

This database then requires me to provide fonts using `resvg_options_load_font_data` so that they can be used to render text in the SVG I've loaded. I believe a copy of the font data is made [here](https://github.com/linebender/resvg/blob/main/crates/c-api/lib.rs#L404-L405).

Since reusing the `usvg::Options` is not possible in my use-case, I was hoping there was a way I can create an independent `fontdb` database and simply use that every time I create a new `usvg::Options` struct so that I can load fonts into the database directly and reuse them in every new SVG I load.

I was requesting help on how I can create a `usvg::Options` struct with default options like [here](https://github.com/linebender/resvg/blob/main/crates/c-api/lib.rs#L120-L124), but provide my own `fontdb` database with pre-loaded fonts rather than using the default empty one that is unique to every new `usvg::Options` struct.

I know the C-API wasn't meant for such flexibility, but I really need this functionality and I'm fine with modifying the rust code on my end to make this work.

**Comment by RazrFalcon** [comment]
Oh, if you're using C API then it's more complicated. I'm not sure if it would be possible to have a shared `fontdb` exposed via C API.

>This database then requires me to provide fonts using resvg_options_load_font_data so that they can be used to render text in the SVG I've loaded.

You can use `resvg_options_load_font_file` or `resvg_options_load_system_fonts`. This will not load anything into the memory.

For now, I would suggest sharing `resvg_options` instead of `fontdb` itself.
